services:
  server:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    environment:
      DEFAULT_DOMAIN: ${DEFAULT_DOMAIN}
      COOKIE_SECURE: ${COOKIE_SECURE}
    ports:
      - "${PORT}:${PORT}"
    command: sh -c "npm run migrate && npm ${START_COMMAND}"
    env_file:
      - .env.${ENV_NAME}

