name: Deploy Kutt on VM via SSH

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.VM_PORT }} ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Set ENV for test/prod
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "ENV_NAME=prod" >> $GITHUB_ENV
          else
            echo "ENV_NAME=test" >> $GITHUB_ENV
          fi

      - name: Deploy to VM
        run: |
          ssh -p ${{ secrets.VM_PORT }} ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} <<EOF
            cd ~/kutt
            git pull origin ${{ github.ref_name }}
            make up ENV_NAME=${{ env.ENV_NAME }}
          EOF
